name: Auto Deploy from Notion

on:
  # Manuel tetikleme
  workflow_dispatch:
  
  # Notion webhook'u için
  repository_dispatch:
    types: [notion-update]
  
  # Scheduled backup (her 2 saatte bir kontrol)
  schedule:
    - cron: '0 */2 * * *'  # Her 2 saatte bir

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          # Remove cache since we don't have lock file
          
      - name: Install dependencies
        run: npm install
        
      - name: Build site
        run: npm run build
        env:
          NOTION_PAGE_ID: ${{ secrets.NOTION_PAGE_ID }}
          NOTION_ACCESS_TOKEN: ${{ secrets.NOTION_ACCESS_TOKEN }}
          
      - name: Generate sitemap
        run: npm run postbuild
        
      - name: Show build success
        run: echo "✅ GitHub Actions build completed successfully!"
        
      # Cloudflare steps temporarily disabled for testing
      # - name: List Cloudflare Pages Projects (to find Project ID)
      #   run: |
      #     curl -X GET "https://api.cloudflare.com/client/v4/accounts/${{ secrets.CLOUDFLARE_ACCOUNT_ID }}/pages/projects" \
      #       -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
      #       -H "Content-Type: application/json" || echo "Need Account ID first"
      #       
      # - name: Try Cloudflare Pages Deploy (will show available projects if fails)
      #   run: |
      #     echo "If Project ID not found, we'll get list of available projects from error"
      #     curl -X GET "https://api.cloudflare.com/client/v4/pages/projects" \
      #       -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
      #       -H "Content-Type: application/json"